apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: echo-command
  labels:
    knative.dev/type: "function"
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/botless/commands/cmd/core/
            env:
            - name: TARGET
              value: "http://default-broker.default.svc.cluster.local"
            - name: STRICT_TYPE
              value: "botless.bot.command.echo"
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: echo-command
spec:
  filter:
    sourceAndType:
      type: botless.bot.command.echo
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: echo-command




